### ISSUE TITLE
Use logger.info instead of println

### ISSUE THREAD

**Issue by ben-manes** [kordamp/jandex-gradle-plugin#1]
While a useful message when implementing, it isn't helpful during normal builds. What about moving this to `logger.info` instead of being displayed to the console by default?

```
> Task :caffeine:jandex
Index has been written to /Users/ben/projects/caffeine/caffeine/build/resources/main/META-INF/jandex.idx
```

https://github.com/kordamp/jandex-gradle-plugin/blob/8fce40e08d8ce425454113894ad440775e9fa2ac/src/main/groovy/org/kordamp/gradle/plugin/jandex/tasks/JandexHelper.groovy#L69

**Comment by aalmiray** [comment]
Release `0.7.0` contains the fix.

**Comment by ben-manes** [comment]
thanks! :)
