### ISSUE TITLE
Jcenter dependency issue with maven-model-builder/3.6.3

### ISSUE THREAD

**Issue by elmsleypass** [kordamp/jandex-gradle-plugin#10]
Using this:
plugins {
    id 'org.kordamp.gradle.jandex' version '0.9.0'
}

I'm getting:

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.apache.maven:maven-model-builder:3.6.3.
     Required by:
         project : > org.kordamp.gradle.jandex:org.kordamp.gradle.jandex.gradle.plugin:0.9.0 > org.kordamp.gradle:jandex-gradle-plugin:0.9.0 > org.kordamp.gradle:base-gradle-plugin:0.42.1
      > Could not resolve org.apache.maven:maven-model-builder:3.6.3.
         > Could not get resource 'https://plugins.gradle.org/m2/org/apache/maven/maven-model-builder/3.6.3/maven-model-builder-3.6.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/apache/maven/maven-model-builder/3.6.3/maven-model-builder-3.6.3.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by aalmiray** [comment]
This might not be an issue on the plugin itself rather it's likely a change made at the Gradle Plugin Portal due to the sunsetting of JCenter. You can define the following in your `settings.gradle`

```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.kordamp.gradle.jandex' version '0.9.0'
    }
}
```

**Comment by elmsleypass** [comment]
THanks.
