### ISSUE TITLE
java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented

### ISSUE THREAD

**Issue by re-thc** [kordamp/jandex-gradle-plugin#18]
Running this with Gradle `7.5-rc-1` and Java 18.

Getting the following error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.indexFile(JandexMain.java:172)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:160)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:147)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2812)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2883)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.execute(JandexMain.java:98)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.run(JandexMain.java:124)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.main(JandexMain.java:111)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 8 more`

**Comment by aalmiray** [comment]
This is strange. The source does not make reference to internal APIs, it's written in Java so there should not be a dependence on an specific Gradle version as it happens when Groovy code is compiled AFAICT https://github.com/kordamp/jandex-gradle-plugin/blob/master/src/main/java/org/kordamp/gradle/plugin/jandex/tasks/JandexMain.java

**Comment by re-thc** [comment]
I just tried this on an empty/blank Quarkus project and it builds. Once the `jandex-gradle-plugin` is added it fails. Either jandex or this plugin but if it's jandex it should fail without this plugin since Quarkus uses it under the hood?

**Comment by re-thc** [comment]
https://github.com/gradle/gradle/issues/14727 could be this bug? Is there a way we can work around it?

**Comment by aalmiray** [comment]
Do you have a reproducible project?

**Comment by aalmiray** [comment]
Do you get the failure with an earlier Gradle version? say 7.4?

**Comment by re-thc** [comment]
7.4.2 is fine. Failure is with 7.5-rc-1. Could be a gradle bug itself or a change of APIs / functionality that has resulted in this. Don't have a specific project yet. Just went to the Quarkus website, checked out a sample and added this plugin to it and triggered the issue.

**Comment by aalmiray** [comment]
The plugin reads compiled classes from the output of the `main` resourceSet, as is. It may be the case those classes have the missing annotation applied to them. The classpath passed to Jandex may not contain the annotation class anymore in 7.5

I don't have access to a computer right now but perhaps running a simple project in debug mode with 7.4.2 vs 7.5 should result in logging the execution classpath used by the JandexMain class. With any luck this should show if a JAR is missing. If not then the annotation used to be located in an existing JAR. 

In any case I don't think there's a workaround if Gradle 7.5 is required. If my suspicion is correct then reading classes to be processed must be done in a different way.

**Comment by aalmiray** [comment]
Turns out the bug is in setting up the classpath that invokes the JavaExec type that runs JandexMain. I know how to fix this. Expect a release in the coming days.

**Comment by re-thc** [comment]
Any luck on fixing this? Thanks!

**Comment by gbloggs** [comment]
I'm just building against the released version of gradle, 7.5 and getting this error.
` ``
    id "org.kordamp.gradle.jandex" version "0.12.0"
    id 'io.quarkus' version '2.11.0.Final'

``` 
------------------------------------------------------------
Gradle 7.5                                                  
------------------------------------------------------------
                                                            
Build time:   2022-07-14 12:48:15 UTC                       
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103      

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (GraalVM Community 17.0.1+12-jvmci-21.3-b05)
OS:           Windows 10 10.0 amd64

```


```

**Comment by gsmet** [comment]
@aalmiray hey. Any chance this issue could be fixed? It's blocking the Quarkus upgrade to Gradle 7.5.

Thanks!

**Comment by aalmiray** [comment]
@gsmet currently looking at it. It appears I'll have to switch to Gradle's Worker API to make it work. Thing is, I'm still learning how to use said API. Hope to get a release ready this week.

**Comment by aalmiray** [comment]
@gsmet version `0.13.0` has just been released with the fix. Please let me know if there any further changes are required.

**Comment by glefloch** [comment]
Thanks @aalmiray, I will update quarkus sample projects
