### ISSUE TITLE
Jandex 3.0

### ISSUE THREAD

**Issue by Ladicek** [kordamp/jandex-gradle-plugin#21]
Hi, Jandex maintainer here. Thanks for maintaining this Gradle plugin!

I'd like to bring up the topic of Jandex 3.0. There's a bunch of changes, some of them breaking. The full list is available in the issue tracker: https://github.com/smallrye/jandex/milestone/3 and there will be detailed release announcement coming (the release should be in a few days).

Two of those changes are relevant to this project:

1. The groupId changed from `org.jboss` to `io.smallrye`.
2. The `Indexer.index()` method now returns `void`.

I can see two ways how this plugin could support Jandex 3.0:

1. Drop compatibility with Jandex 2.x and force Jandex 3.0 on everyone. The code changes would look like this I believe: https://github.com/Ladicek/jandex-gradle-plugin/commits/jandex3
2. Try to keep this plugin compatible with both Jandex 2.x and 3.0. This seems impossible due to item 2 above (which is a binary breaking change), but using some [bytecode magic](https://github.com/dmlloyd/bridger), the `Indexer` class in Jandex 3.0 will carry a synthetic `index()` method returning `ClassInfo` (which will always be `null`). Hence, compatibility should be achievable.

I  believe that long term, migrating to Jandex 3.0 (1st option) is in everyone's best interest, but short term, the 2nd option seems like a good idea. When invoking `Indexer.index()`, this Gradle plugin actually already checks if the result is `null`, so using this Jandex Gradle plugin compiled against Jandex 2.4 with Jandex 3.0 at runtime should work. There will just be no logging, which I think is acceptable. The only change required would likely be in the `JandexPlugin` class, where the `jandex` configuration is created. This change should be enough:

```java
jandexConfiguration.defaultDependencies(new Action<DependencySet>() {
    @Override
    void execute(DependencySet dependencies) {
        String version = jandexExtension.version.get()
        if (version.startsWith("2.") || version.startsWith("1.")) {
            dependencies.add(project.dependencies.create('org.jboss:jandex:' + version))
        } else {
            dependencies.add(project.dependencies.create('io.smallrye:jandex:' + version))
        }
    }
})
```

If you want to check anything, the Jandex 3.0.0-RC3 release is already in Maven Central and should be identical to the final release (unless I uncover some last-minute issue). Importantly, it has the synthetic `index()` method returning `ClassInfo`, as mentioned above.

WDYT?

(I may be missing something, obviously. Please let me know if so. Thanks!)

**Comment by aalmiray** [comment]
@Ladicek thank you for the heads up!

@gsmet WDYT wrt Quarkus compatibility? So far this plugin has had a low version number. A binary break such as embracing Jandex 3.0 would likely mean moving the plugin to `1.0.0`.

**Comment by Ladicek** [comment]
I'm not sure if you follow semver or not, but since this plugin is still on the 0.x version, I'd say `0.14` (or some other `0.x` down the line) can make breaking changes just fine. If this plugin was on 1.x, then requiring Jandex 3 would indeed necessitate bumping to 2.0.

(At the same time, this plugin is apparently used a lot, and so should probably be on 1.x already).

From Quarkus perspective, I'm actually on that team and I'm working on bumping Jandex in Quarkus as we speak :-) This is actually why I opened this issue -- I had a successful build of Quarkus (`mvn clean install`, so no tests using containers yet) yesterday with all tests passing with the exception of Gradle plugin tests. I'm trying to figure that out now :-)

**Comment by aalmiray** [comment]
Right. I could release `0.14.0` with Jandex 3 only but that might set wrong compatibility expectations. I rather bump this plugin to `1.0.0` if Jandex 3 is used. This will signal consumers that they must continue using `0.13.x` if Jandex 2 is required (as it's the case for recent versions of Helidon IIRC)

**Comment by Ladicek** [comment]
Your call, obviously :-) If you want to explore the compatibility path I outlined above, let me know and I'll be glad to help.
