### ISSUE TITLE
Gradle 7 makes optimizations disabled

### ISSUE THREAD

**Issue by Xendar** [kordamp/jandex-gradle-plugin#9]
Hello,

I have a Quarkus based project using Gradle, and wanted to update from Gradle `6.8` to `7`.
I am simply registering the plugin id:
```
plugins {
    id 'org.kordamp.gradle.jandex' version '0.9.0'
}
```

Now I build time, I get the following warnings:
```
> Task :core:jar
Execution optimizations have been disabled for task ':core:jar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\path\to\project\core\build\resources\main'. Reason: Task ':core:jar' uses this output of task ':core:jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```
I get it for tasks `compileTestJava`, `test`, `jacocoTestReport`...

If I add an explicit dependency like this:
```
jar {
    dependsOn 'jandex'
}
```
It seems to solve the issue. However, I am not sure if we should do this explicitly, or if the plugin should do it auto-magically...

It's a private project that I cannot share, but I can try things out if needed :)

**Comment by aalmiray** [comment]
It may be related to the default behavior of including the generated index as part of the `processResources` set of files

https://github.com/kordamp/jandex-gradle-plugin/blob/master/src/main/groovy/org/kordamp/gradle/plugin/jandex/JandexPlugin.groovy#L70-L78

I must confess I have no clue why Gradle 7.0 suddenly complains about this. This Gradle release has added stringent rules on how certain elements may be accessed & configured. will have to conduct a review of what has changed and figure something out to avoid additional explicit configuration (if possible) as you have shown.

**Comment by Xendar** [comment]
> It may be related to the default behavior of including the generated index as part of the `processResources` set of files
> 
> https://github.com/kordamp/jandex-gradle-plugin/blob/master/src/main/groovy/org/kordamp/gradle/plugin/jandex/JandexPlugin.groovy#L70-L78
> 
> I must confess I have no clue why Gradle 7.0 suddenly complains about this. This Gradle release has added stringent rules on how certain elements may be accessed & configured. will have to conduct a review of what has changed and figure something out to avoid additional explicit configuration (if possible) as you have shown.

Thanks Andres for the quick reply! Hope this won't bring too much trouble...

**Comment by aalmiray** [comment]
Well, can't tell right now but one thing is for sure, Gradle will keep moving forward and they'll keep changing APIs and breaking compatibility as they see fit. Hope we can keep up with the changes.

**Comment by Xendar** [comment]
Hey @aalmiray 
Just to let you know that I tried the new version `0.10.0` and while the message no more appears for the `jar` task it still appears for the `compileIntegrationTestJava`, `compileTestJava`, `test` and `jacocoTestReport` tasks.
Not sure though if I need to open a new issue (or not) for this, please let me know

**Comment by aalmiray** [comment]
I'm afraid there's little that can be done from the plugin side at the moment. Gradle has changed the rules once again, see https://github.com/kordamp/jandex-gradle-plugin/issues/11

What must happen now is that consumers (such as yourself) must explicitly declare dependencies between tasks as the plugin can't possibly know all potential consuming tasks ahead of time.
